name: Deploy Express App

on:
  push:
    branches:
      - live
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean server directory except ecosystem.config.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            shopt -s extglob
            cd /var/www/matthewbowman.uk/public_api
            rm -rf !("ecosystem.config.js")

      - name: Upload app files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/var/www/matthewbowman.uk/public_api/"
          strip_components: 0

      - name: Install dependencies and reload PM2 process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/matthewbowman.uk/public_api
            npm ci
            pm2 start ecosystem.config.js || pm2 reload ecosystem.config.js
